Repository yangtori0407/coffice, pull requests merged in 2025-06, with the labels that each got.

#22 [Feat/#18] 공지사항 crud
  pom.xml
  src/main/java/com/coffice/app/files/FileConfig.java
  src/main/java/com/coffice/app/files/FileDownView.java
  src/main/java/com/coffice/app/files/FileManager.java
  src/main/java/com/coffice/app/files/FileVO.java
  src/main/java/com/coffice/app/page/Pager.java
  src/main/java/com/coffice/app/posts/notice/NoticeController.java
  src/main/java/com/coffice/app/posts/notice/NoticeDAO.java
  src/main/java/com/coffice/app/posts/notice/NoticeService.java
  src/main/java/com/coffice/app/posts/notice/NoticeVO.java
  src/main/resources/database/mappers/NoticeMapper.xml
  src/main/resources/database/mappers/SampleMapper.xml
  src/main/resources/static/images/3.png
  src/main/resources/static/js/coffice/noticeAdd.js
  src/main/resources/static/js/coffice/noticeDetail.js
  src/main/resources/static/js/coffice/noticeUpdate.js
  src/main/webapp/WEB-INF/views/commons/ajaxResult.jsp
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/notice/add.jsp
  src/main/webapp/WEB-INF/views/notice/detail.jsp
  src/main/webapp/WEB-INF/views/notice/list.jsp
  src/main/webapp/WEB-INF/views/notice/update.jsp
  src/main/webapp/WEB-INF/views/templates/sidebar.jsp
  src/test/java/com/coffice/app/posts/notice/NoticeDAOTest.java
Labels: 🌟Feature

#25 Feat/#21 캘린더 공휴일api추가
  src/main/java/com/coffice/app/events/EventController.java
  src/main/java/com/coffice/app/events/schedule/ScheduleController.java
  src/main/java/com/coffice/app/events/vacation/VacationController.java
  src/main/java/com/coffice/app/home/HomeController.java
  src/main/resources/static/js/calendar/fullCalendar.js
  src/main/resources/static/js/calendar/homeCalendar.js
  src/main/webapp/WEB-INF/views/events/schedule.jsp
  src/main/webapp/WEB-INF/views/events/vacation.jsp
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/templates/fullCalendar.jsp
  src/main/webapp/WEB-INF/views/templates/homeCalendar.jsp
  src/main/webapp/WEB-INF/views/templates/sidebar.jsp
Labels: 🌟Feature

#32 [fix/#31] 조직도 모달 버전 수정
  src/main/webapp/WEB-INF/views/templates/ocModal.jsp
Labels: 🐞bug

#35 Feat/#30 익명게시판 댓글
  src/main/java/com/coffice/app/files/FileVO.java
  src/main/java/com/coffice/app/posts/board/BoardController.java
  src/main/java/com/coffice/app/posts/board/BoardDAO.java
  src/main/java/com/coffice/app/posts/board/BoardSerivce.java
  src/main/java/com/coffice/app/posts/board/CommentVO.java
  src/main/resources/database/mappers/BoardMapper.xml
  src/main/resources/static/js/posts/boardDetail.js
  src/main/resources/static/js/posts/noticeAdd.js
  src/main/resources/static/js/posts/noticeDetail.js
  src/main/resources/static/js/posts/noticeUpdate.js
  src/main/webapp/WEB-INF/views/board/add.jsp
  src/main/webapp/WEB-INF/views/board/detail.jsp
  src/main/webapp/WEB-INF/views/notice/add.jsp
  src/main/webapp/WEB-INF/views/notice/detail.jsp
  src/main/webapp/WEB-INF/views/notice/update.jsp
Labels: 🌟Feature

#44 feat: #43 stomp 연결
  pom.xml
  src/main/java/com/coffice/app/chat/ChatController.java
  src/main/java/com/coffice/app/chat/config/WebSocketConfig.java
  src/main/java/com/coffice/app/chat/config/WebSocketStompBrokerConfig.java
  src/main/java/com/coffice/app/chat/config/handler/ChatWebSocketHandler.java
Labels: 🌟Feature

#48 [Refactor/#46] 문서 결재선 참조선 문서양식 vo 수정
  src/main/java/com/coffice/app/documents/DocumentController.java
  src/main/java/com/coffice/app/documents/DocumentVO.java
  src/main/java/com/coffice/app/documents/forms/FormVO.java
  src/main/java/com/coffice/app/documents/lines/ApprovalLineVO.java
  src/main/java/com/coffice/app/documents/lines/ReferenceLineVO.java
Labels: 🛠️Refactor

#59 [Refactor/#49] 문서결재 서비스 및 매퍼 프로퍼티명 수정
  src/main/java/com/coffice/app/documents/DocumentController.java
  src/main/java/com/coffice/app/documents/DocumentDAO.java
  src/main/java/com/coffice/app/documents/DocumentService.java
  src/main/java/com/coffice/app/documents/DocumentVO.java
  src/main/resources/database/mappers/DocumentMapper.xml
  src/main/resources/static/js/document/makeSetting.js
  src/main/webapp/WEB-INF/views/document/detail.jsp
  src/main/webapp/WEB-INF/views/document/form/form10.jsp
  src/main/webapp/WEB-INF/views/document/form/form11.jsp
  src/main/webapp/WEB-INF/views/document/form/form12.jsp
  src/main/webapp/WEB-INF/views/document/form/form13.jsp
  src/main/webapp/WEB-INF/views/document/list.jsp
Labels: 🛠️Refactor

#61 Feat/#57 채팅방 화면 구성
  src/main/java/com/coffice/app/chat/ChatController.java
  src/main/java/com/coffice/app/chat/ChatDAO.java
  src/main/java/com/coffice/app/chat/ChatService.java
  src/main/java/com/coffice/app/chat/vo/ChatAddVO.java
  src/main/java/com/coffice/app/chat/vo/ChatContentsVO.java
  src/main/java/com/coffice/app/chat/vo/ChatFilesVO.java
  src/main/java/com/coffice/app/chat/vo/ChatPersonVO.java
  src/main/java/com/coffice/app/chat/vo/ChatRoomVO.java
  src/main/resources/database/mappers/ChatMapper.xml
  src/main/resources/static/js/chat/add.js
  src/main/webapp/WEB-INF/views/chat/chatRoom.jsp
  src/main/webapp/WEB-INF/views/chat/main.jsp
Labels: 🌟Feature

#65 Feat/#54 일정관리 일정공휴일조회
  src/main/java/com/coffice/app/events/EventController.java
  src/main/java/com/coffice/app/events/EventVO.java
  src/main/java/com/coffice/app/events/schedule/ScheduleDAO.java
  src/main/java/com/coffice/app/events/schedule/ScheduleService.java
  src/main/resources/database/mappers/HolidayMapper.xml
  src/main/resources/database/mappers/ScheduleMapper.xml
  src/main/resources/static/js/calendar/homeCalendar.js
  src/main/resources/static/js/calendar/scheduleCalendar.js
  src/main/resources/static/js/calendar/vacationCalendar.js
  src/main/webapp/WEB-INF/views/events/schedule.jsp
  src/main/webapp/WEB-INF/views/templates/ocModal.jsp
Labels: 🌟Feature

#73 [Feat/#60] 문서 결재처리 및 단계별 결재진행 구현
  src/main/java/com/coffice/app/documents/DocumentController.java
  src/main/java/com/coffice/app/documents/DocumentDAO.java
  src/main/java/com/coffice/app/documents/DocumentService.java
  src/main/java/com/coffice/app/documents/lines/ApprovalLineVO.java
  src/main/resources/database/mappers/DocumentMapper.xml
  src/main/resources/static/images/signs/3.png
  src/main/resources/static/images/signs/coffice.png
  src/main/resources/static/js/document/makeSetting.js
  src/main/webapp/WEB-INF/views/document/detail.jsp
  src/main/webapp/WEB-INF/views/document/list.jsp
  src/main/webapp/WEB-INF/views/templates/sidebar.jsp
Labels: 🌟Feature

#77 Feat/#76 메인 페이지 공지사항 추가
  src/main/java/com/coffice/app/home/HomeController.java
  src/main/java/com/coffice/app/posts/notice/NoticeDAO.java
  src/main/java/com/coffice/app/posts/notice/NoticeService.java
  src/main/resources/database/mappers/NoticeMapper.xml
  src/main/webapp/WEB-INF/views/index.jsp
Labels: 🌟Feature

#79 feat/#78 조직도 ajax처리 (User 데이터처리)
  src/main/java/com/coffice/app/users/UserController.java
  src/main/java/com/coffice/app/users/UserDAO.java
  src/main/java/com/coffice/app/users/UserService.java
  src/main/resources/database/mappers/UserMapper.xml
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/templates/ocModal.jsp
Labels: 🌟Feature

#92 Refator/#36 게시판 댓글 작성자 추가 및 mapper 수정
  src/main/java/com/coffice/app/posts/board/BoardController.java
  src/main/java/com/coffice/app/posts/notice/NoticeController.java
  src/main/resources/database/mappers/BoardMapper.xml
  src/main/resources/static/js/posts/boardDetail.js
  src/main/webapp/WEB-INF/views/board/add.jsp
  src/main/webapp/WEB-INF/views/board/detail.jsp
  src/main/webapp/WEB-INF/views/notice/detail.jsp
  src/test/java/com/coffice/app/posts/board/BoardDAOTest.java
  src/test/java/com/coffice/app/posts/notice/NoticeDAOTest.java
Labels: 🛠️Refactor

#94 Feat/#93 모달로 채팅방 사람 추가하기
  src/main/resources/static/js/chat/add.js
  src/main/webapp/WEB-INF/views/chat/addChat.jsp
  src/main/webapp/WEB-INF/views/templates/ocModal.jsp
  src/main/webapp/WEB-INF/views/templates/sample.jsp
Labels: 🌟Feature

#106 fix:#105 dev 오류 수정
  pom.xml
  src/main/java/com/coffice/app/users/UserController.java
Labels: 🛠️Refactor

#111 Feat/#95 채팅방 알림 기능
  src/main/java/com/coffice/app/chat/ChatController.java
  src/main/java/com/coffice/app/chat/ChatDAO.java
  src/main/java/com/coffice/app/chat/ChatService.java
  src/main/java/com/coffice/app/chat/vo/ChatContentsVO.java
  src/main/java/com/coffice/app/chat/vo/ChatPersonVO.java
  src/main/java/com/coffice/app/chat/vo/ChatRoomVO.java
  src/main/java/com/coffice/app/home/HomeController.java
  src/main/resources/database/mappers/ChatMapper.xml
  src/main/resources/static/css/chatAlert.css
  src/main/resources/static/js/chat/chatStomp.js
  src/main/resources/static/js/notification/notification.js
  src/main/webapp/WEB-INF/views/chat/chatRoom.jsp
  src/main/webapp/WEB-INF/views/chat/main.jsp
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/templates/footModal.jsp
  src/main/webapp/WEB-INF/views/templates/header.jsp
  src/main/webapp/WEB-INF/views/templates/top.jsp
Labels: 🌟Feature

#115 Fix:#114 게시판/메신저 헤더 제목 수정
  src/main/java/com/coffice/app/chat/ChatController.java
  src/main/java/com/coffice/app/home/HomeController.java
  src/main/java/com/coffice/app/posts/board/BoardController.java
  src/main/java/com/coffice/app/posts/notice/NoticeController.java
  src/main/webapp/WEB-INF/views/board/detail.jsp
  src/main/webapp/WEB-INF/views/board/list.jsp
  src/main/webapp/WEB-INF/views/notice/detail.jsp
  src/main/webapp/WEB-INF/views/notice/list.jsp
  src/main/webapp/WEB-INF/views/templates/top.jsp
Labels: 🛠️Refactor

#121 Refactor/#119 유저 아이디 쿠키에 담아서 꺼내 쓰기
  src/main/java/com/coffice/app/security/LoginSuccessHandler.java
  src/main/resources/static/js/chat/chatStomp.js
  src/main/resources/static/js/chat/main.js
  src/main/resources/static/js/notification/notification.js
  src/main/webapp/WEB-INF/views/chat/addChat.jsp
  src/main/webapp/WEB-INF/views/chat/chatRoom.jsp
  src/main/webapp/WEB-INF/views/templates/ocModal.jsp
  src/main/webapp/WEB-INF/views/templates/top.jsp
Labels: 🛠️Refactor

#123 feat: #120 일괄수정/단일수정보완
  src/main/java/com/coffice/app/events/EventController.java
  src/main/java/com/coffice/app/events/schedule/ScheduleDAO.java
  src/main/java/com/coffice/app/events/schedule/ScheduleService.java
  src/main/resources/database/mappers/ScheduleMapper.xml
  src/main/resources/static/js/calendar/scheduleCalendar.js
Labels: 🌟Feature

#131 feat: #124 일정삭제-완-
  src/main/java/com/coffice/app/events/EventController.java
  src/main/java/com/coffice/app/events/schedule/ScheduleDAO.java
  src/main/java/com/coffice/app/events/schedule/ScheduleService.java
  src/main/java/com/coffice/app/events/schedule/ScheduleVO.java
  src/main/resources/database/mappers/ScheduleMapper.xml
  src/main/resources/static/js/calendar/scheduleCalendar.js
  src/main/webapp/WEB-INF/views/events/schedule.jsp
Labels: 🌟Feature

#135 [feat: #134] 반려 상태 업데이트 및 반려 관련 내용 조회
  src/main/java/com/coffice/app/documents/DocumentController.java
  src/main/java/com/coffice/app/documents/DocumentDAO.java
  src/main/java/com/coffice/app/documents/DocumentService.java
  src/main/resources/database/mappers/DocumentMapper.xml
  src/main/resources/static/js/document/toReject.js
  src/main/webapp/WEB-INF/views/document/form/variableForm.jsp
  src/main/webapp/WEB-INF/views/document/list.jsp
  src/main/webapp/WEB-INF/views/document/modal/rejectReasonModal.jsp
  src/main/webapp/WEB-INF/views/templates/ocModal.jsp
Labels: 🌟Feature

#141 Feat/#109 헤더에 알림 띄우기
  src/main/java/com/coffice/app/notification/NotificationController.java
  src/main/java/com/coffice/app/notification/NotificationDAO.java
  src/main/java/com/coffice/app/notification/NotificationService.java
  src/main/java/com/coffice/app/notification/NotificationVO.java
  src/main/java/com/coffice/app/posts/notice/NoticeService.java
  src/main/resources/database/mappers/NotificationMapper.xml
  src/main/resources/static/css/chatAlert.css
  src/main/resources/static/js/notification/notification.js
  src/main/webapp/WEB-INF/views/templates/top.jsp
Labels: 🌟Feature

#143 Fix:142 모달 로직 수정
  src/main/webapp/WEB-INF/views/templates/ocModal.jsp
Labels: 🛠️Refactor

#145 Fix/#144 알림 헤더 js 오류 수정
  src/main/resources/static/js/notification/notification.js
Labels: 🛠️Refactor

#146 Feat/#97 익명게시판 댓글 알림 기능
  src/main/java/com/coffice/app/notification/NotificationService.java
  src/main/java/com/coffice/app/posts/board/BoardController.java
  src/main/java/com/coffice/app/posts/board/BoardDAO.java
  src/main/java/com/coffice/app/posts/board/BoardSerivce.java
  src/main/resources/database/mappers/BoardMapper.xml
  src/main/resources/static/css/chatAlert.css
  src/main/resources/static/js/notification/notification.js
  src/main/resources/static/js/posts/boardDetail.js
  src/main/resources/static/js/posts/noticeDetail.js
  src/main/webapp/WEB-INF/views/templates/footModal.jsp
  src/main/webapp/WEB-INF/views/templates/top.jsp
Labels: 🌟Feature

#150 Feat/#147 익명게시판 대댓글 알림 기능
  src/main/java/com/coffice/app/notification/NotificationService.java
  src/main/java/com/coffice/app/posts/board/BoardDAO.java
  src/main/java/com/coffice/app/posts/board/BoardSerivce.java
  src/main/resources/database/mappers/BoardMapper.xml
  src/main/resources/static/js/notification/notification.js
  src/main/webapp/WEB-INF/views/board/add.jsp
  src/main/webapp/WEB-INF/views/board/detail.jsp
  src/main/webapp/WEB-INF/views/notice/add.jsp
Labels: 🌟Feature

#152 Feat/#132 휴가관리 휴가신청
  src/main/java/com/coffice/app/events/EventController.java
  src/main/java/com/coffice/app/events/EventVO.java
  src/main/java/com/coffice/app/events/schedule/ScheduleService.java
  src/main/java/com/coffice/app/events/vacation/VacationDAO.java
  src/main/java/com/coffice/app/events/vacation/VacationService.java
  src/main/java/com/coffice/app/events/vacation/VacationVO.java
  src/main/resources/database/mappers/VacationMapper.xml
  src/main/resources/static/js/calendar/scheduleCalendar.js
  src/main/resources/static/js/calendar/vacationCalendar.js
  src/main/webapp/WEB-INF/views/events/schedule.jsp
  src/main/webapp/WEB-INF/views/templates/top.jsp
Labels: 🌟Feature

#156 feat: #100 공휴일scheduleInsert
  src/main/java/com/coffice/app/events/holidays/HolidayDAO.java
  src/main/java/com/coffice/app/events/holidays/HolidayService.java
  src/main/resources/database/mappers/HolidayMapper.xml
Labels: 🌟Feature

#158 Feat/#157 공휴일schedule test
  src/main/java/com/coffice/app/events/holidays/HolidayService.java
Labels: 🌟Feature

#162 [Feat/#149] 문서 파일 첨부 관련 기능 구현
  src/main/java/com/coffice/app/documents/DocumentController.java
  src/main/java/com/coffice/app/documents/DocumentDAO.java
  src/main/java/com/coffice/app/documents/DocumentService.java
  src/main/java/com/coffice/app/files/FileDownView.java
  src/main/java/com/coffice/app/files/FileManager.java
  src/main/resources/database/mappers/DocumentMapper.xml
  src/main/resources/static/js/document/toTemporary.js
  src/main/resources/static/js/document/writeJs.js
  src/main/webapp/WEB-INF/views/document/form/selectForm.jsp
  src/main/webapp/WEB-INF/views/document/form/variableForm.jsp
  src/main/webapp/WEB-INF/views/templates/ocModal.jsp
Labels: 🌟Feature

#164 Feat/#37 이메일 리스트 조회
  src/main/java/com/coffice/app/message/MessageCheckVO.java
  src/main/java/com/coffice/app/message/MessageController.java
  src/main/java/com/coffice/app/message/MessageDAO.java
  src/main/java/com/coffice/app/message/MessageMailConfig.java
  src/main/java/com/coffice/app/message/MessageService.java
  src/main/java/com/coffice/app/message/MessageVO.java
  src/main/java/com/coffice/app/notification/NotificationService.java
  src/main/java/com/coffice/app/posts/notice/NoticeController.java
  src/main/resources/database/mappers/MessageMapper.xml
  src/main/resources/static/js/message/messageAdd.js
  src/main/resources/static/js/notification/notification.js
  src/main/resources/static/js/sidebar.js
  src/main/webapp/WEB-INF/views/message/add.jsp
  src/main/webapp/WEB-INF/views/message/receive.jsp
  src/main/webapp/WEB-INF/views/message/send.jsp
  src/main/webapp/WEB-INF/views/message/success.jsp
  src/main/webapp/WEB-INF/views/templates/ocModal.jsp
  src/main/webapp/WEB-INF/views/templates/sidebar.jsp
Labels: 🌟Feature

#166 Fix/#165 오류 수정
  src/main/java/com/coffice/app/posts/notice/NoticeController.java
  src/main/webapp/WEB-INF/views/templates/sidebar.jsp
Labels: 🛠️Refactor

#170 [Fix: #169] 조직도 버튼 중복 코드 제거
  src/main/webapp/WEB-INF/views/templates/ocModal.jsp
Labels: 🐞bug

#173 feat :#140 사원리스트 및 마이페이지
  src/main/java/com/coffice/app/CofficeApplication.java
  src/main/java/com/coffice/app/attendance/AttendanceController.java
  src/main/java/com/coffice/app/attendance/AttendanceDAO.java
  src/main/java/com/coffice/app/attendance/AttendanceScheduler.java
  src/main/java/com/coffice/app/attendance/AttendanceService.java
  src/main/java/com/coffice/app/attendance/AttendanceVO.java
  src/main/java/com/coffice/app/employee/CalendarUtils.java
  src/main/java/com/coffice/app/employee/EmployeeController.java
  src/main/java/com/coffice/app/employee/EmployeeDAO.java
  src/main/java/com/coffice/app/employee/EmployeeService.java
  src/main/java/com/coffice/app/employee/EmployeeVO.java
  src/main/java/com/coffice/app/mail/NaverMailSender.java
  src/main/java/com/coffice/app/security/SecurityConfig.java
  src/main/java/com/coffice/app/users/UserController.java
  src/main/java/com/coffice/app/users/UserService.java
  src/main/java/com/coffice/app/users/UserVO.java
  src/main/resources/database/mappers/AttendanceMapper.xml
  src/main/resources/database/mappers/EmployeeMapper.xml
  src/main/resources/static/css/employee/detail.css
  src/main/webapp/WEB-INF/views/attendance/statusUpdate.jsp
  src/main/webapp/WEB-INF/views/employee/detail.jsp
  src/main/webapp/WEB-INF/views/employee/list.jsp
  src/main/webapp/WEB-INF/views/employee/update.jsp
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/templates/sidebar.jsp
  src/main/webapp/WEB-INF/views/user/mypage.jsp
  src/main/webapp/WEB-INF/views/user/update.jsp
  src/test/java/com/coffice/app/employee/EmployeeDAOTest.java
Labels: 🌟Feature

#174 Fix/#172 댓글 알림 로직 변경
  src/main/java/com/coffice/app/notification/NotificationService.java
Labels: 🛠️Refactor

#176 Feat/#160 휴가수정 마이페이지연결
  src/main/java/com/coffice/app/events/EventController.java
  src/main/java/com/coffice/app/events/vacation/VacationDAO.java
  src/main/java/com/coffice/app/events/vacation/VacationService.java
  src/main/resources/database/mappers/VacationMapper.xml
  src/main/resources/static/js/calendar/vacationCalendar.js
  src/main/webapp/WEB-INF/views/events/schedule.jsp
  src/main/webapp/WEB-INF/views/index.jsp
Labels: 🌟Feature

#178 fix: #175 사이드바 수정
  src/main/webapp/WEB-INF/views/templates/sidebar.jsp
Labels: 🛠️Refactor

#182 Feat/#167 이메일 상세보기
  src/main/java/com/coffice/app/message/MessageController.java
  src/main/java/com/coffice/app/message/MessageDAO.java
  src/main/java/com/coffice/app/message/MessageService.java
  src/main/java/com/coffice/app/message/MessageVO.java
  src/main/resources/database/mappers/MessageMapper.xml
  src/main/webapp/WEB-INF/views/message/detail.jsp
  src/main/webapp/WEB-INF/views/message/receive.jsp
  src/main/webapp/WEB-INF/views/message/send.jsp
Labels: 🌟Feature

#184 Feat/#183 메일 삭제
  src/main/java/com/coffice/app/message/MessageCheckVO.java
  src/main/java/com/coffice/app/message/MessageController.java
  src/main/java/com/coffice/app/message/MessageDAO.java
  src/main/java/com/coffice/app/message/MessageService.java
  src/main/java/com/coffice/app/message/MessageVO.java
  src/main/resources/database/mappers/MessageMapper.xml
  src/main/resources/static/js/message/messageDetail.js
  src/main/webapp/WEB-INF/views/message/detail.jsp
Labels: 🌟Feature

#186 feat: #179 관리자 사원근태 수정
  src/main/java/com/coffice/app/attendance/AttendanceController.java
  src/main/java/com/coffice/app/attendance/AttendanceDAO.java
  src/main/java/com/coffice/app/attendance/AttendanceService.java
  src/main/java/com/coffice/app/attendance/AttendanceVO.java
  src/main/resources/database/mappers/AttendanceMapper.xml
  src/main/resources/static/css/attendance/updateStatus.css
  src/main/resources/static/js/attendance/updateStatus.js
  src/main/webapp/WEB-INF/views/attendance/statusUpdate.jsp
Labels: 🌟Feature

#190 Feat/#185 메일 답장 기능
  src/main/java/com/coffice/app/message/MessageController.java
  src/main/java/com/coffice/app/message/MessageDAO.java
  src/main/java/com/coffice/app/message/MessageService.java
  src/main/java/com/coffice/app/message/MessageVO.java
  src/main/resources/database/mappers/MessageMapper.xml
  src/main/resources/static/js/message/messageReply.js
  src/main/webapp/WEB-INF/views/message/detail.jsp
  src/main/webapp/WEB-INF/views/message/reply.jsp
  src/main/webapp/WEB-INF/views/message/success.jsp
Labels: 🌟Feature

#194 Feat/#191 메일 페이지네이션/검색
  src/main/java/com/coffice/app/message/MessageController.java
  src/main/java/com/coffice/app/message/MessageDAO.java
  src/main/java/com/coffice/app/message/MessageService.java
  src/main/resources/database/mappers/MessageMapper.xml
  src/main/webapp/WEB-INF/views/message/receive.jsp
  src/main/webapp/WEB-INF/views/message/send.jsp
Labels: 🌟Feature

#196 fix: #192 마이페이지 및 로그아웃 페이지 css 보완
  src/main/resources/static/css/user/afterLogin.css
  src/main/webapp/WEB-INF/views/user/afterLogout.jsp
  src/main/webapp/WEB-INF/views/user/mypage.jsp
  src/main/webapp/WEB-INF/views/user/register.jsp
Labels: 🛠️Refactor

#202 Feat/#195 메일 알림
  src/main/java/com/coffice/app/message/MessageService.java
  src/main/java/com/coffice/app/notification/NotificationService.java
  src/main/resources/static/js/notification/notification.js
Labels: 🌟Feature

#207 Feat/#203 휴가 알림
  src/main/java/com/coffice/app/events/EventController.java
  src/main/java/com/coffice/app/notification/NotificationDAO.java
  src/main/java/com/coffice/app/notification/NotificationService.java
  src/main/resources/database/mappers/NotificationMapper.xml
  src/main/resources/static/js/notification/notification.js
Labels: 🌟Feature

#208 Feat/#204 결재 알림
  src/main/java/com/coffice/app/notification/NotificationService.java
  src/main/resources/static/js/notification/notification.js
Labels: 🌟Feature

#209 Feat/#181 마이페이지 연차설정
  src/main/java/com/coffice/app/events/EventController.java
  src/main/java/com/coffice/app/events/EventUtility.java
  src/main/java/com/coffice/app/events/EventVO.java
  src/main/java/com/coffice/app/events/holidays/HolidayVO.java
  src/main/java/com/coffice/app/events/schedule/ScheduleVO.java
  src/main/java/com/coffice/app/events/vacation/AnnualLeaveDAO.java
  src/main/java/com/coffice/app/events/vacation/AnnualLeaveService.java
  src/main/java/com/coffice/app/events/vacation/AnnualLeaveVO.java
  src/main/java/com/coffice/app/events/vacation/VacationService.java
  src/main/java/com/coffice/app/events/vacation/VacationVO.java
  src/main/java/com/coffice/app/users/AnnualLeaveVO.java
  src/main/java/com/coffice/app/users/UserController.java
  src/main/resources/database/mappers/AnnualLeaveMapper.xml
  src/main/resources/database/mappers/VacationMapper.xml
  src/main/resources/static/js/calendar/vacationCalendar.js
  src/main/webapp/WEB-INF/views/user/annualLeaveHistory.jsp
  src/main/webapp/WEB-INF/views/user/mypage.jsp
  src/main/webapp/WEB-INF/views/user/vacationHistory.jsp
Labels: 🌟Feature

#210 Feat/#205 메일 수신확인
  src/main/java/com/coffice/app/message/MessageController.java
  src/main/java/com/coffice/app/message/MessageDAO.java
  src/main/java/com/coffice/app/message/MessageService.java
  src/main/java/com/coffice/app/message/MessageVO.java
  src/main/resources/database/mappers/BoardMapper.xml
  src/main/resources/database/mappers/MessageMapper.xml
  src/main/resources/database/mappers/NoticeMapper.xml
  src/main/resources/static/js/message/messageReceive.js
  src/main/resources/static/js/message/messageSend.js
  src/main/webapp/WEB-INF/views/board/list.jsp
  src/main/webapp/WEB-INF/views/message/receive.jsp
  src/main/webapp/WEB-INF/views/message/send.jsp
  src/main/webapp/WEB-INF/views/notice/list.jsp
Labels: 🌟Feature

#215 feat/ #201 근태 바 그래프
  src/main/java/com/coffice/app/attendance/AttendanceController.java
  src/main/java/com/coffice/app/attendance/AttendanceDAO.java
  src/main/java/com/coffice/app/attendance/AttendanceService.java
  src/main/java/com/coffice/app/attendance/AttendanceStatusCountVO.java
  src/main/java/com/coffice/app/users/UserController.java
  src/main/resources/database/mappers/AttendanceMapper.xml
  src/main/resources/static/css/user/mypage.css
  src/main/webapp/WEB-INF/views/board/detail.jsp
  src/main/webapp/WEB-INF/views/board/list.jsp
  src/main/webapp/WEB-INF/views/employee/list.jsp
  src/main/webapp/WEB-INF/views/user/mypage.jsp
Labels: 🌟Feature

#218 Refactor/#214 cron수정 배포환경설정
  src/main/java/com/coffice/app/events/holidays/HolidayService.java
  src/main/java/com/coffice/app/users/UserController.java
  src/main/resources/static/js/user/history.js
  src/main/webapp/WEB-INF/views/user/vacationHistory.jsp
Labels: 🛠️Refactor

#225 Fix/#219 알림 버그 수정
  src/main/java/com/coffice/app/chat/ChatController.java
  src/main/java/com/coffice/app/message/MessageController.java
  src/main/java/com/coffice/app/message/MessageService.java
  src/main/java/com/coffice/app/notification/NotificationDAO.java
  src/main/java/com/coffice/app/notification/NotificationService.java
  src/main/java/com/coffice/app/posts/board/BoardController.java
  src/main/java/com/coffice/app/posts/board/BoardSerivce.java
  src/main/java/com/coffice/app/posts/board/BoardVO.java
  src/main/java/com/coffice/app/posts/notice/NoticeController.java
  src/main/java/com/coffice/app/posts/notice/NoticeDAO.java
  src/main/java/com/coffice/app/posts/notice/NoticeService.java
  src/main/java/com/coffice/app/posts/notice/NoticeVO.java
  src/main/resources/database/mappers/NotificationMapper.xml
  src/main/resources/static/js/notification/notification.js
  src/main/webapp/WEB-INF/views/board/list.jsp
  src/main/webapp/WEB-INF/views/notice/list.jsp
Labels: 🐞bug, 🛠️Refactor

#227 refactor: #226 반차적용, 승인거절추가
  src/main/java/com/coffice/app/events/EventController.java
  src/main/java/com/coffice/app/events/vacation/VacationDAO.java
  src/main/java/com/coffice/app/events/vacation/VacationService.java
  src/main/java/com/coffice/app/events/vacation/VacationVO.java
  src/main/resources/database/mappers/VacationMapper.xml
  src/main/resources/static/js/calendar/vacationCalendar.js
  src/main/webapp/WEB-INF/views/events/schedule.jsp
Labels: 🛠️Refactor

#232 Feat/#230 문서 파트 결재 알림 기능 추가
  src/main/java/com/coffice/app/documents/DocumentController.java
  src/main/java/com/coffice/app/documents/DocumentService.java
  src/main/resources/database/mappers/DocumentMapper.xml
  src/main/webapp/WEB-INF/views/document/modal/signModal.jsp
Labels: 🌟Feature

#233 fix: #224 사이드바
  src/main/java/com/coffice/app/attendance/AttendanceDAO.java
  src/main/java/com/coffice/app/attendance/AttendanceScheduler.java
  src/main/java/com/coffice/app/attendance/AttendanceService.java
  src/main/java/com/coffice/app/employee/EmployeeController.java
  src/main/java/com/coffice/app/users/EmployeeRoleDAO.java
  src/main/java/com/coffice/app/users/RoleDAO.java
  src/main/java/com/coffice/app/users/UserController.java
  src/main/java/com/coffice/app/users/UserService.java
  src/main/resources/database/mappers/AttendanceMapper.xml
  src/main/resources/database/mappers/EmployeeRoleMapper.xml
  src/main/resources/database/mappers/RoleMapper.xml
  src/main/resources/static/css/sidebar.css
  src/main/webapp/WEB-INF/views/templates/sidebar.jsp
Labels: 🛠️Refactor
